update scripts for submission

diff --git a/scripts/per_case/Snakefile b/scripts/per_case/Snakefile
--- a/scripts/per_case/Snakefile
+++ b/scripts/per_case/Snakefile
@@ -110,7 +110,7 @@ rule check_output:
 rule download_normal_tumor_single:
     output:
         read_1=data_dir+"/{SRR}/{SRR}_1.fastq.gz",
-        read_2=data_dir+"/{SRR}/{SRR}_1.fastq.gz",
+        read_2=data_dir+"/{SRR}/{SRR}_2.fastq.gz",
         sra=temp(data_dir+"/{SRR}/{SRR}.sra"),
         md5_out=temp(data_dir+"/{SRR}/md5_out_{SRR}")
     params:
@@ -151,14 +151,17 @@ rule download_normal_tumor_single:
         fi
         '''
 
+# def get_individual_SRR(wildcards):
+#     return wildcards.subset.split('-')
+
 rule download_normal_tumor_merged:
     output:
         read_1=data_dir+"/{SRR}/{SRR}_1.fastq.gz",
-        read_2=data_dir+"/{SRR}/{SRR}_1.fastq.gz",
-        temp(expand(data_dir+"/{{SRR}}/{individual_SRR}.sra", individual_SRR = lambda wc: wc.get("SRR").split('-'))),
-        temp(expand(data_dir+"/{{SRR}}/{individual_SRR}_1.fastq", individual_SRR = lambda wc: wc.get("SRR").split('-'))),
-        temp(expand(data_dir+"/{{SRR}}/{individual_SRR}_2.fastq", individual_SRR = lambda wc: wc.get("SRR").split('-'))),
-        temp(expand(data_dir+"/{{SRR}}/md5_out_{individual_SRR}", individual_SRR = lambda wc: wc.get("SRR").split('-'))),
+        read_2=data_dir+"/{SRR}/{SRR}_2.fastq.gz",
+        # temp(expand(data_dir+"/{{SRR}}/{individual_SRR}.sra", individual_SRR = get_individual_SRR)),
+        # temp(expand(data_dir+"/{{SRR}}/{individual_SRR}_1.fastq", individual_SRR = get_individual_SRR)),
+        # temp(expand(data_dir+"/{{SRR}}/{individual_SRR}_2.fastq", individual_SRR = get_individual_SRR)),
+        # temp(expand(data_dir+"/{{SRR}}/md5_out_{individual_SRR}", individual_SRR = get_individual_SRR)),
         accession_list=temp(data_dir+"/{SRR}/{SRR}.list")
     params:
         run_accession=lambda wc: wc.get("SRR"),
@@ -181,30 +184,30 @@ rule download_normal_tumor_merged:
         > {params.read_dir}/{params.run_accession}_1.fastq
         > {params.read_dir}/{params.run_accession}_2.fastq
         while read SRR; do
-            if [[ ! -e {params.read_dir}/$SRR.sra ]]; then 
-                prefetch $SRR -o {params.read_dir}/$SRR.sra
+            if [[ ! -e {params.read_dir}/${{SRR}}.sra ]]; then 
+                prefetch ${{SRR}} -o {params.read_dir}/${{SRR}}.sra
             fi
-            vdb-validate {params.read_dir}/$SRR.sra &> {params.read_dir}/md5_out_$SRR
-            stat=`grep "'$SRR.sra' is consistent" {params.read_dir}/md5_out_$SRR`
+            vdb-validate {params.read_dir}/${{SRR}}.sra &> {params.read_dir}/md5_out_${{SRR}}
+            stat=`grep "'${{SRR}}.sra' is consistent" {params.read_dir}/md5_out_${{SRR}}`
             count=0
             while [[ -z $stat ]] && [[ $count -lt {params.retry_times} ]]; do # check if the string is empty
-                prefetch $SRR -o {params.read_dir}/$SRR.sra
-                vdb-validate {params.read_dir}/$SRR.sra &> {params.read_dir}/md5_out_$SRR
-                stat=`grep "'$SRR.sra' is consistent" {params.read_dir}/md5_out_$SRR`
+                prefetch ${{SRR}} -o {params.read_dir}/${{SRR}}.sra
+                vdb-validate {params.read_dir}/${{SRR}}.sra &> {params.read_dir}/md5_out_${{SRR}}
+                stat=`grep "'${{SRR}}.sra' is consistent" {params.read_dir}/md5_out_${{SRR}}`
                 (( count++ ))
             done
-            if [[ -e {params.read_dir}/$SRR.sra ]]; then
-                fasterq-dump --split-files -O {params.read_dir} {params.read_dir}/$SRR.sra &>> {log}
-                echo "Download success for $SRR" >> {log}
+            if [[ -e {params.read_dir}/${{SRR}}.sra ]]; then
+                fasterq-dump --split-files -O {params.read_dir} {params.read_dir}/${{SRR}}.sra &>> {log}
+                echo "Download success for ${{SRR}}" >> {log}
             else
-                echo "Download failed for $SRR" >> {log}; exit 1;
+                echo "Download failed for ${{SRR}}" >> {log}; exit 1;
             fi
-            cat {params.read_dir}/$SRR_1.fastq >> {params.read_dir}/{params.run_accession}_1.fastq
-            cat {params.read_dir}/$SRR_2.fastq >> {params.read_dir}/{params.run_accession}_2.fastq
-            # rm {params.read_dir}/$SRR.sra
-            # rm {params.read_dir}/md5_out_$SRR
-            # rm {params.read_dir}/$SRR_1.fastq
-            # rm {params.read_dir}/$SRR_2.fastq
+            cat {params.read_dir}/${{SRR}}_1.fastq >> {params.read_dir}/{params.run_accession}_1.fastq
+            cat {params.read_dir}/${{SRR}}_2.fastq >> {params.read_dir}/{params.run_accession}_2.fastq
+            rm {params.read_dir}/${{SRR}}.sra
+            rm {params.read_dir}/md5_out_${{SRR}}
+            rm {params.read_dir}/${{SRR}}_1.fastq
+            rm {params.read_dir}/${{SRR}}_2.fastq
         done < {output.accession_list}
         gzip -f {params.read_dir}/{params.run_accession}_1.fastq
         gzip -f {params.read_dir}/{params.run_accession}_2.fastq
@@ -224,6 +227,8 @@ rule read_mapping:
     params:
         out_dir=bam_out,
         ref=config['in']['ref']
+    wildcard_constraints:
+        SRR=".*[A-Z]RR[0-9]+"
     conda:
         config['envs']['wesenv']
     threads:
@@ -249,6 +254,8 @@ rule get_header:
     output:
         header=bam_out+"/header_{SRR}",
         bam=bam_out+"/{SRR}.bam"
+    wildcard_constraints:
+        SRR=".*[A-Z]RR[0-9]+"
     conda:
         config['envs']['wesenv']
     threads:
@@ -267,6 +274,8 @@ rule remove_unmapped:
         header=bam_out+"/header_{SRR}"
     output:
         cleaned_sam=temp(bam_out+"/{SRR}-cleaned.sam")
+    wildcard_constraints:
+        SRR=".*[A-Z]RR[0-9]+"
     conda:
         config['envs']['wesenv']
     params:
@@ -284,6 +293,8 @@ rule sort_sam:
         cleaned_sam=bam_out+"/{SRR}-cleaned.sam"
     output:
         sorted_bam=temp(bam_out+"/{SRR}_rg_added_sorted.bam"),
+    wildcard_constraints:
+        SRR=".*[A-Z]RR[0-9]+"
     conda:
         config['envs']['wesenv']
     threads:
